// Generated by CoffeeScript 1.6.3
(function() {
  var NetsoulConnect, nsconnect, prefix;

  NetsoulConnect = require('..').connects.unixSocket;

  nsconnect = new NetsoulConnect({
    path: '/tmp/netsoul.sock'
  });

  prefix = "DEBUG> ";

  nsconnect.on('buffer', function(buffer) {
    return console.log("" + prefix + "buffer", buffer);
  });

  nsconnect.on('data', function(data) {
    return console.log("" + prefix + "data", data);
  });

  nsconnect.on('nsconnect', function() {
    return console.log("" + prefix + "nsconnect");
  });

  nsconnect.on('disconnect', function() {
    return console.log("" + prefix + "disconnect");
  });

  nsconnect.on('error', function(error) {
    console.log("" + prefix + "error", error);
    return process.exit(1);
  });

  nsconnect.on('message', function(msg) {
    console.log("" + prefix + "message", msg);
    if (msg.split[0] === 'ping') {
      return nsconnect.send('pong');
    }
  });

  nsconnect.connect();

}).call(this);
